import unittest

from app.agents.crewai_adapter import WorkerExecutionPlan
from app.approval.service import HumanApprovalEngine
from app.core.config import Settings
from app.core.contracts import ArchitecturePlan, ExecutionResult, ExecutionStatus, HumanDecisionType, TaskSpec, WorkerSpec
from app.core.states import WorkflowState
from app.execution import ExecutionBackend, ExecutionBackendInfo, ExecutionGateway
from app.intake.service import IntakeService
from app.orchestration.service import IntegratedOrchestrationError, IntegratedOrchestrator
from app.runtime.service import RuntimeCoordinator
from app.session.manager import SessionManager
from app.workers.models import WorkerInstance
from app.workers.runtime import WorkerExecutionTask, WorkerRuntimeAdapter


class FakeBackend(ExecutionBackend):
    @property
    def info(self):
        return ExecutionBackendInfo("test", "Test")

    def execute(self, request):
        return ExecutionResult(
            execution_id=request.execution_id,
            status=ExecutionStatus.SUCCESS,
            exit_code=0,
            stdout="ok",
            stderr="",
            duration_ms=1,
            backend="test",
        )


class FakeWorkerAgent:
    def build_execution_plan(self, *, worker, task, context=None):
        return WorkerExecutionPlan(
            worker_id=worker.worker_id,
            task_id=task.task_id,
            summary="generated by fake worker agent",
            execution_task=WorkerExecutionTask(
                task=task,
                language="python",
                code="print('ok')",
            ),
        )


def settings():
    return Settings(
        gemini_api_key="test-key",
        gemini_model_architect="architect",
        gemini_model_worker="worker",
        gemini_model_supervisor="supervisor",
        gemini_temperature=0.2,
        max_workers=4,
        min_workers=3,
        default_execution_timeout_seconds=60,
        max_uploads_per_message=20,
        max_upload_size_mb=100,
        execution_backend="test",
        execution_gateway_url=None,
        execution_gateway_token=None,
    )


def make_ready_run():
    sessions = SessionManager()
    approvals = HumanApprovalEngine()
    intake = IntakeService(session_manager=sessions, settings=settings())
    coordinator = RuntimeCoordinator(
        session_manager=sessions,
        intake_service=intake,
        approval_engine=approvals,
    )
    result = coordinator.start_run("Build a test project")
    plan = ArchitecturePlan(
        plan_id="plan-test",
        objective="Build a test project",
        acceptance_criteria=("produce a successful execution",),
        workers=(
            WorkerSpec(
                worker_id="worker-1",
                role="builder",
                mission="build the test project",
                deliverables=("result",),
            ),
        ),
    )
    sessions.set_architecture_plan(result.run_id, plan)
    gate = approvals.request_gate(
        run_id=result.run_id,
        kind="ARCHITECTURE",
        title="Approve architecture",
        prompt="approve",
    )
    sessions.transition(result.run_id, WorkflowState.ARCHITECTING)
    sessions.transition(result.run_id, WorkflowState.WAITING_ARCHITECT_APPROVAL)
    decision = approvals.resolve_gate(
        gate_id=gate.gate_id,
        decision=HumanDecisionType.APPROVE,
        feedback="approved",
    )
    coordinator.apply_architecture_decision(decision)
    return coordinator, sessions, result.run_id


class IntegratedOrchestratorTests(unittest.TestCase):
    def make_orchestrator(self):
        coordinator, sessions, run_id = make_ready_run()
        gateway = ExecutionGateway(backends=(FakeBackend(),), settings=settings())
        runtime = WorkerRuntimeAdapter(gateway=gateway, session_manager=sessions)
        orchestrator = IntegratedOrchestrator(
            coordinator=coordinator,
            session_manager=sessions,
            worker_runtime=runtime,
            worker_agent=FakeWorkerAgent(),
        )
        return orchestrator, sessions, run_id

    def test_approved_run_executes_and_reaches_final_gate(self):
        orchestrator, sessions, run_id = self.make_orchestrator()

        result = orchestrator.execute_run(run_id)

        self.assertEqual(result.qa_result.status.value, "pass")
        self.assertIsNotNone(result.final_gate_id)
        self.assertEqual(
            sessions.get_context(run_id).state,
            WorkflowState.WAITING_FINAL_APPROVAL,
        )
        self.assertEqual(len(result.execution_results), 1)
        self.assertEqual(len(sessions.snapshot(run_id).worker_outputs), 1)

    def test_execution_requires_gate_a(self):
        sessions = SessionManager()
        approvals = HumanApprovalEngine()
        intake = IntakeService(session_manager=sessions, settings=settings())
        coordinator = RuntimeCoordinator(
            session_manager=sessions,
            intake_service=intake,
            approval_engine=approvals,
        )
        run = coordinator.start_run("Build")
        plan = ArchitecturePlan(
            plan_id="plan",
            objective="Build",
            acceptance_criteria=("done",),
            workers=(WorkerSpec(worker_id="w", role="builder", mission="build"),),
        )
        sessions.set_architecture_plan(run.run_id, plan)
        gateway = ExecutionGateway(backends=(FakeBackend(),), settings=settings())
        orchestrator = IntegratedOrchestrator(
            coordinator=coordinator,
            session_manager=sessions,
            worker_runtime=WorkerRuntimeAdapter(gateway=gateway, session_manager=sessions),
            worker_agent=FakeWorkerAgent(),
        )

        with self.assertRaises(IntegratedOrchestrationError):
            orchestrator.execute_run(run.run_id)


if __name__ == "__main__":
    unittest.main()
